Release workflow
Draegerwerk/t2iapi pull request #10
Opened 2022-11-18 13:30 UTC by ldeichmann

Add automatic release deployment to t2iapi for both Java and Python. Tags will be released as pre-releases on github, unless they begin with a "v", in which case they are considered proper releases and won't include a build number in the deployments.

# Checklist

The following aspects have been respected by the author of this pull request, confirmed by both pull request assignee **and** reviewer:

* Changelog update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* README update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer

2022-11-18 13:39 UTC, ldeichmann commented
The resulting Github releases can be seen here https://github.com/ldeichmann/t2iapi/releases

2022-11-22 08:04 UTC, leon1995 requested changes

2022-11-22 08:04 UTC, leon1995 commented on python/setup.py
>      dev_release_segment = f'dev{os.getenv("GITHUB_RUN_NUMBER", default=0)}'
move below the `is_release_version` check

2022-11-22 08:24 UTC, antipovi approved these changes

2022-11-22 08:30 UTC, leon1995 approved these changes

2022-11-22 08:43 UTC, merged