Manipuliation transition component activation
Draegerwerk/t2iapi pull request #37
Opened 2023-05-26 10:42 UTC by NerijusKondrotas

// Describe the purpose of the pull request here and remove this line. Keep the checklist.

# Checklist

The following aspects have been respected by the author of this pull request, confirmed by both pull request assignee **and** reviewer:

* Changelog update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* README update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer

2023-05-26 11:45 UTC, antipovi requested changes

2023-05-26 11:45 UTC, antipovi commented on src/t2iapi/activation_state/activation_state_requests.proto
> +message SetTransitionComponentActivationRequest {
Set and Transition doesnt make sense imo
i think "Set" can be dropped from manipulation name, also from the rpc call

2023-05-26 11:45 UTC, antipovi commented on src/t2iapi/activation_state/activation_state_requests.proto
> +Request to set the ActivationState of the component or metric with the given handle and the start and
misleading description, the objective of the manipulation is not very clear, write the expectancy
transition from one state to another is not mentioned

2023-05-30 07:53 UTC, antipovi requested changes

2023-05-30 07:53 UTC, antipovi commented on src/t2iapi/activation_state/activation_state_requests.proto
> +    string handle = 1;  // descriptor handle of the descriptor for which the ActivationState shall be set
@ActivationState

2023-05-30 07:53 UTC, antipovi commented on src/t2iapi/activation_state/service.proto
> +  The ActivationState transition from the start to the end of the DeviceComponent or Metric with the given handle.
@ActivationState

2023-05-30 07:53 UTC, antipovi commented on CHANGELOG.md
> +- manipulation TransitionComponentActivation for metrics
the manipulation is not only for metrics

2023-05-30 15:14 UTC, maximilianpilz commented
replace

> // Describe the purpose of the pull request here and remove this line. Keep the checklist.

in the initial comment

2023-05-30 17:03 UTC, maximilianpilz requested changes
replace

> // Describe the purpose of the pull request here and remove this line. Keep the checklist.

in the initial comment

2023-06-01 10:14 UTC, antipovi approved these changes

2023-06-01 14:20 UTC, maximilianpilz approved these changes

2023-06-01 14:20 UTC, merged