Adapt descriptions for manipulations
Draegerwerk/t2iapi pull request #39
Opened 2023-05-31 07:05 UTC by jannast

change descriptions for the manipulations: SetAlertActivation, SetComponentActivation, SetAlarmSignalInactivationState, 
    SetAlertSystemNotFunctional, SetLocationDetail, RemoveAllContextStateValidators, SetContextStateAssociation,
    CreateContextStateWithAssociation, CreateContextStateWithAssociationAndUniqueIdentification, 
    CreateContextStateWithAssocIdentificationAndValidator, RemoveIdentificationOfContextState,
    ChangeIdentificationOfContextState, CreateContextStateWithAssocAndSpecificValidator,
    SetClockDevice, SetLanguage, SetNoValue, SetMetricValuesWithQualityMode

# Checklist

The following aspects have been respected by the author of this pull request, confirmed by both pull request assignee **and** reviewer:

* Changelog update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* README update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer

2023-06-02 12:15 UTC, antipovi requested changes

2023-06-05 05:09 UTC, jannast commented on src/t2iapi/device/service.proto
done

2023-06-05 06:41 UTC, antipovi approved these changes

2023-06-05 06:52 UTC, belagertem commented
Open topic: sdccc does not always need manipulations where the result is persistent until the next manipulation.

2023-06-09 08:18 UTC, belagertem approved these changes

2023-06-12 09:35 UTC, a-kleinf approved these changes

2023-06-12 09:37 UTC, merged