Added trigger any descriptor update manipulation
Draegerwerk/t2iapi pull request #50
Opened 2023-07-10 17:56 UTC by ben-Draeger

The TriggerDescriptorUpdate manipulation requires specifying the descriptor that is to be updated. However, for most descriptor types, there are devices that do not support updating them. Also, to the best of my knowledge, there are no type of descriptor that exists in every Mdib and can be always be updated.  
Hence, when the goal is to trigger a DescriptorManipulationReport with parts of type UPT, then the only way to find a descriptor in the Mdib, which can be updated is trial and error. However, trial and error would involve calling the TriggerDescriptorUpdate manipulation quite often, which is burdensome when the manipulation has to be performed manually. 

Hence, we introduce a new manipulation TriggerAnyDescriptorUpdate which essentially does the same as TriggerDescriptorUpdate, but does not require the caller to specify the descriptor. Rather, it chooses the descriptor itself - and as long as the device has descriptos that can be updated, it should of course choose one of them.

# Checklist

The following aspects have been respected by the author of this pull request, confirmed by both pull request assignee **and** reviewer:

* Changelog update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* README update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer

2023-07-12 13:07 UTC, belagertem commented on src/t2iapi/device/service.proto
> +    The descriptor handle to update may be chosen by the device. It is expected that this manipulation succeeds
What do you think of the following to mitigate different interpretations:

```suggestion
    The descriptor to update has to be chosen by the device. It is expected that this manipulation succeeds
```

2023-07-12 13:13 UTC, antipovi commented
cant the manipulation "TriggerReport" with ReportType REPORT_TYPE_DESCRIPTION_MODIFICATION_REPORT be used instead?

2023-07-12 13:18 UTC, belagertem commented
> cant the manipulation "TriggerReport" with ReportType REPORT_TYPE_DESCRIPTION_MODIFICATION_REPORT be used instead?

If "TriggerReport" with with ReportType REPORT_TYPE_DESCRIPTION_MODIFICATION_REPORT is used, you would get a DescriptionModificationReport, but no guarantee that it would contain a ReportPart with ModificationType UPT.

2023-07-13 07:55 UTC, belagertem submitted a review, later dismissed

2023-07-13 09:20 UTC, antipovi requested changes

2023-07-13 09:20 UTC, antipovi commented on src/t2iapi/device/service.proto
> +    This manipulation shall result in a msg:DescriptionModificationReport message with a report part with
```suggestion
    This manipulation shall result in a msg:DescriptionModificationReport message with a msg:ReportPart/@ModificationType = "Upt".
```

2023-07-13 11:58 UTC, belagertem submitted a review, later dismissed

2023-07-13 12:44 UTC, belagertem approved these changes

2023-07-13 13:04 UTC, merged