SetComponentActivationAndSetOperatingMode and SetAlertActivationAndSe…
Draegerwerk/t2iapi pull request #62
Opened 2023-09-05 12:10 UTC by NerijusKondrotas

…tOperatingMode manipulations

// Describe the purpose of the pull request here and remove this line. Keep the checklist.

# Checklist

The following aspects have been respected by the author of this pull request, confirmed by both pull request assignee **and** reviewer:

* Changelog update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* README update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer

2023-09-05 14:16 UTC, a-kleinf commented on src/t2iapi/combined/service.proto
> +      returns (t2iapi.context.SetAlertActivationAndSetOperatingModeResponse);
must be BasicResponse

2023-09-05 14:19 UTC, a-kleinf commented on src/t2iapi/combined/combined_requests.proto
> +    AlertActivation activation = 2; // value to set as the ActivationState value
must be t2iapi.activation_state.AlertActivation

2023-09-05 14:19 UTC, a-kleinf commented on src/t2iapi/combined/combined_requests.proto
> +    ComponentActivation activation = 2; // value to set as the ActivationState value
t2iapi.activation_state.ComponentActivation
and add import:
import "t2iapi/activation_state/types.proto";

2023-09-05 14:20 UTC, a-kleinf commented on src/t2iapi/combined/service.proto
> +      returns (t2iapi.context.SetComponentActivationAndSetOperatingModeResponse);
and import:
import "t2iapi/basic_responses.proto";

2023-09-05 14:26 UTC, a-kleinf commented on src/t2iapi/combined/combined_requests.proto
> + */
adapt to something like:
/*
Request to set the ActivationState of the alert with the given handle to the requested AlertActivation value and to set the OperatingMode of the operation with the given handle to the requested OperatingMode value.
 */

2023-09-05 14:28 UTC, a-kleinf commented on src/t2iapi/combined/combined_requests.proto
> + */
adapt to something like:
/*
Request to set the ActivationState of the component or metric with the given handle to the requested ComponentActivation value and to set the OperatingMode of the operation with the given handle to the requested OperatingMode value.
*/

2023-09-05 14:29 UTC, a-kleinf commented on src/t2iapi/combined/service.proto
> +  */
use the description from the request and add
 /* The manipulated states shall be persistent until a next manipulation call or an SDC operation invocation.
  If the device is not able to maintain the static states, it shall return RESULT_NOT_SUPPORTED.*/

2023-09-05 14:29 UTC, a-kleinf commented on src/t2iapi/combined/service.proto
> +  */
use the description from the request and add
 /* The manipulated states shall be persistent until a next manipulation call or an SDC operation invocation.
  If the device is not able to maintain the static states, it shall return RESULT_NOT_SUPPORTED.*/

2023-09-06 15:07 UTC, a-kleinf requested changes

2023-09-06 15:07 UTC, a-kleinf commented on src/t2iapi/combined/combined_requests.proto
> +}
in both new mesages - adapt the wordning of the attributes to be consistent, see also CreateContextStateWithAssociationAndSetOperatingModeRequest

2023-09-07 09:17 UTC, a-kleinf approved these changes

2023-09-07 10:01 UTC, ldeichmann approved these changes

2023-09-07 11:22 UTC, merged