adapt wording
Draegerwerk/t2iapi pull request #63
Opened 2023-09-06 07:30 UTC by pstaeck

// Describe the purpose of the pull request here and remove this line. Keep the checklist.

# Checklist

The following aspects have been respected by the author of this pull request, confirmed by both pull request assignee **and** reviewer:

* Changelog update (necessity checked and entry added or not added respectively)
  * [x] Pull Request Assignee
  * [x] Reviewer
* README update (necessity checked and entry added or not added respectively)
  * [x] Pull Request Assignee
  * [x] Reviewer

2023-09-06 15:00 UTC, a-kleinf requested changes

2023-09-07 05:34 UTC, pstaeck commented on src/t2iapi/context/context_requests.proto
> +Request to create or adapt a pm:AbstractContextState instance with a given @ContextAssociation and a given number
done for all CreateContext...Requests

2023-09-07 05:35 UTC, pstaeck commented on src/t2iapi/context/service.proto
> +  Create or adapt a pm:AbstractContextState instance with the given @ContextAssociation value for the given descriptor handle
done for all CreateContext... rpcs

2023-09-07 08:46 UTC, a-kleinf approved these changes

2023-09-07 08:50 UTC, merged