add InsertContainmentTreeEntryForSequenceId
Draegerwerk/t2iapi pull request #91
Opened 2024-09-12 09:51 UTC by antipovi-draeger

Add manipulation InsertContainmentTreeEntryForSequenceId

# Checklist

The following aspects have been respected by the author of this pull request, confirmed by both pull request assignee **and** reviewer:

* Changelog update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer
* README update (necessity checked and entry added or not added respectively)
  * [ ] Pull Request Assignee
  * [ ] Reviewer

2024-09-16 11:37 UTC, ldeichmann requested changes
Prefer the BPKP definition

2024-09-16 12:31 UTC, ldeichmann requested changes

2024-09-16 12:31 UTC, ldeichmann commented on src/t2iapi/device/service.proto
> +    - metric with the handle "metric_1" is still present in the current MDIB
```suggestion
    - metric with the handle "metric_1" is still present in the current MDIB and represents the *same* metric as in @SequenceID "123"
```

2024-09-16 12:31 UTC, ldeichmann commented on src/t2iapi/device/service.proto
> +    absent in the current MDIB, it shall be inserted and its (new) handle shall be returned. If the
```suggestion
    absent in the current MDIB, it shall be inserted and its handle in the current MDIB shall be returned. If the
```

2024-09-16 12:31 UTC, ldeichmann commented on src/t2iapi/device/service.proto
> +    - MDS with the handle "mds0" is still present in the current MDIB but it's handle changed to "mds10"
```suggestion
    - MDS which had the Handle "mds0" in @SequenceID "123" is still present in the current MDIB, but it's handle changed to "mds10"
```

2024-09-16 12:31 UTC, ldeichmann commented on src/t2iapi/device/service.proto
> +    - channel with handle "channel123" is no longer present in the current MDIB
```suggestion
    - Channel which had the Handle "channel123" in @SequenceID "123" is no longer present in the current MDIB
```

2024-09-16 12:31 UTC, ldeichmann commented on src/t2iapi/device/service.proto
> +    - the (new) handle of the inserted channel is returned
Maybe be concrete about the handle here as well
```suggestion
    - Channel is inserted into the device's current MDIB with handle "channel789"
    - the handle "channel789" is returned
```

2024-09-16 12:31 UTC, ldeichmann commented on src/t2iapi/device/service.proto
> +    - "mds10" is returned since the descriptor handle for that MDS has changed
```suggestion
    - the handle "mds10" is returned as the descriptor handle for that MDS has changed
```

2024-09-16 12:31 UTC, ldeichmann commented on src/t2iapi/device/service.proto
> +    - "metric_1" is returned since the descriptor with this handle it is still available in the current MDIB
```suggestion
    - the handle "metric_1" is returned as the descriptor with this handle it is still available in the current MDIB
```

2024-09-17 13:18 UTC, antipovi-draeger commented on src/t2iapi/device/service.proto
> +    they stay the same.
i like it

2024-09-17 13:24 UTC, pstaeck reviewed
I agree with Lukas remarks. No further findings from my side.

2024-09-17 13:38 UTC, pstaeck requested changes

2024-09-17 13:38 UTC, pstaeck commented on src/t2iapi/device/device_responses.proto
> +BICEPS CONTAINMENT TREE ENTRY (as defined in IEEE Std 11073-10700-2022 in the device's current MDIB.
a braket is missing

2024-09-18 07:15 UTC, antipovi-draeger commented on src/t2iapi/device/device_responses.proto
> +BICEPS CONTAINMENT TREE ENTRY (as defined in IEEE Std 11073-10700-2022 in the device's current MDIB.
done

2024-09-18 08:24 UTC, pstaeck approved these changes

2024-09-19 11:48 UTC, ldeichmann approved these changes

2024-09-19 13:34 UTC, merged